.. activecode:: ch_13_except_pokemon
    :author: Karl Sickendick
    :difficulty: 2.0
    :basecourse: thinkcspy
    :chapter: Exceptions
    :subchapter: Exercises
    :topics: Exceptions/Exercises
    :from_source: F

    Change the first two try/except blocks to catch the exceptions.  Add a try/except block in the correct way to make the third catch, and print "CATCH 3!" only when the exception happens.

    Gotta catch 'em all!
    ~~~~
    try:
        raise RuntimeError("Catch me if you can")
    except NotARealException as e:
        print("CATCH 1!")
    
    try:
        raise NameError("Catch me if you can")
    except NotARealException:
        print("CATCH 2!")

    raise Exception("Catch me if you can!")
    print("CATCH 3!")
    ====
    pass