.. mchoice:: fileEx_catch
    :author: bmiller
    :difficulty: 3.0
    :basecourse: py4e-int
    :chapter: 07-files
    :subchapter: Exercises
    :topics: 07-files/Exercises
    :from_source: T
    :practice: T
    :answer_a: True
    :answer_b: False
    :correct: a
    :feedback_a: Try/except statements are used to prevent an exception from terminating a program.
    :feedback_b: Try/except statements are a catch for programs. What does that mean?

    True or False? Try and except statements are used to catch errors from terminating programs.